#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezerwacje.Data_Access
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BazaRezerwacje")]
	public partial class RezerwacjeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKlienci(Klienci instance);
    partial void UpdateKlienci(Klienci instance);
    partial void DeleteKlienci(Klienci instance);
    partial void InsertImprezy(Imprezy instance);
    partial void UpdateImprezy(Imprezy instance);
    partial void DeleteImprezy(Imprezy instance);
    partial void InsertKoszyk(Koszyk instance);
    partial void UpdateKoszyk(Koszyk instance);
    partial void DeleteKoszyk(Koszyk instance);
    partial void InsertZamowienia(Zamowienia instance);
    partial void UpdateZamowienia(Zamowienia instance);
    partial void DeleteZamowienia(Zamowienia instance);
    partial void InsertZlecenieSzczegoly(ZlecenieSzczegoly instance);
    partial void UpdateZlecenieSzczegoly(ZlecenieSzczegoly instance);
    partial void DeleteZlecenieSzczegoly(ZlecenieSzczegoly instance);
    #endregion
		
		public RezerwacjeDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BazaRezerwacjeConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RezerwacjeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RezerwacjeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RezerwacjeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RezerwacjeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Klienci> Kliencis
		{
			get
			{
				return this.GetTable<Klienci>();
			}
		}
		
		public System.Data.Linq.Table<Imprezy> Imprezies
		{
			get
			{
				return this.GetTable<Imprezy>();
			}
		}
		
		public System.Data.Linq.Table<Koszyk> Koszyks
		{
			get
			{
				return this.GetTable<Koszyk>();
			}
		}
		
		public System.Data.Linq.Table<WidokCenaKoszyka> WidokCenaKoszykas
		{
			get
			{
				return this.GetTable<WidokCenaKoszyka>();
			}
		}
		
		public System.Data.Linq.Table<Zamowienia> Zamowienias
		{
			get
			{
				return this.GetTable<Zamowienia>();
			}
		}
		
		public System.Data.Linq.Table<ZlecenieSzczegoly> ZlecenieSzczegolies
		{
			get
			{
				return this.GetTable<ZlecenieSzczegoly>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Klienci")]
	public partial class Klienci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _KlientID;
		
		private System.Nullable<int> _Wiek;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKlientIDChanging(int value);
    partial void OnKlientIDChanged();
    partial void OnWiekChanging(System.Nullable<int> value);
    partial void OnWiekChanged();
    #endregion
		
		public Klienci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlientID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int KlientID
		{
			get
			{
				return this._KlientID;
			}
			set
			{
				if ((this._KlientID != value))
				{
					this.OnKlientIDChanging(value);
					this.SendPropertyChanging();
					this._KlientID = value;
					this.SendPropertyChanged("KlientID");
					this.OnKlientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wiek", DbType="Int")]
		public System.Nullable<int> Wiek
		{
			get
			{
				return this._Wiek;
			}
			set
			{
				if ((this._Wiek != value))
				{
					this.OnWiekChanging(value);
					this.SendPropertyChanging();
					this._Wiek = value;
					this.SendPropertyChanged("Wiek");
					this.OnWiekChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Imprezy")]
	public partial class Imprezy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ImprezaID;
		
		private string _Nazwa;
		
		private System.Nullable<System.DateTime> _Data;
		
		private string _Miejsce;
		
		private System.Nullable<decimal> _CenaPodstawowa;
		
		private System.Nullable<decimal> _CenaStudent;
		
		private System.Nullable<decimal> _CenaUlgowa;
		
		private System.Nullable<int> _LiczbaBiletow;
		
		private string _Obrazek;
		
		private string _Szczegoly;
		
		private System.Nullable<int> _SprzedaneBilety;
		
		private EntitySet<Koszyk> _Koszyks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnImprezaIDChanging(int value);
    partial void OnImprezaIDChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnDataChanging(System.Nullable<System.DateTime> value);
    partial void OnDataChanged();
    partial void OnMiejsceChanging(string value);
    partial void OnMiejsceChanged();
    partial void OnCenaPodstawowaChanging(System.Nullable<decimal> value);
    partial void OnCenaPodstawowaChanged();
    partial void OnCenaStudentChanging(System.Nullable<decimal> value);
    partial void OnCenaStudentChanged();
    partial void OnCenaUlgowaChanging(System.Nullable<decimal> value);
    partial void OnCenaUlgowaChanged();
    partial void OnLiczbaBiletowChanging(System.Nullable<int> value);
    partial void OnLiczbaBiletowChanged();
    partial void OnObrazekChanging(string value);
    partial void OnObrazekChanged();
    partial void OnSzczegolyChanging(string value);
    partial void OnSzczegolyChanged();
    partial void OnSprzedaneBiletyChanging(System.Nullable<int> value);
    partial void OnSprzedaneBiletyChanged();
    #endregion
		
		public Imprezy()
		{
			this._Koszyks = new EntitySet<Koszyk>(new Action<Koszyk>(this.attach_Koszyks), new Action<Koszyk>(this.detach_Koszyks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImprezaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ImprezaID
		{
			get
			{
				return this._ImprezaID;
			}
			set
			{
				if ((this._ImprezaID != value))
				{
					this.OnImprezaIDChanging(value);
					this.SendPropertyChanging();
					this._ImprezaID = value;
					this.SendPropertyChanged("ImprezaID");
					this.OnImprezaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="VarChar(50)")]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miejsce", DbType="VarChar(50)")]
		public string Miejsce
		{
			get
			{
				return this._Miejsce;
			}
			set
			{
				if ((this._Miejsce != value))
				{
					this.OnMiejsceChanging(value);
					this.SendPropertyChanging();
					this._Miejsce = value;
					this.SendPropertyChanged("Miejsce");
					this.OnMiejsceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaPodstawowa", DbType="Money")]
		public System.Nullable<decimal> CenaPodstawowa
		{
			get
			{
				return this._CenaPodstawowa;
			}
			set
			{
				if ((this._CenaPodstawowa != value))
				{
					this.OnCenaPodstawowaChanging(value);
					this.SendPropertyChanging();
					this._CenaPodstawowa = value;
					this.SendPropertyChanged("CenaPodstawowa");
					this.OnCenaPodstawowaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaStudent", DbType="Money")]
		public System.Nullable<decimal> CenaStudent
		{
			get
			{
				return this._CenaStudent;
			}
			set
			{
				if ((this._CenaStudent != value))
				{
					this.OnCenaStudentChanging(value);
					this.SendPropertyChanging();
					this._CenaStudent = value;
					this.SendPropertyChanged("CenaStudent");
					this.OnCenaStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaUlgowa", DbType="Money")]
		public System.Nullable<decimal> CenaUlgowa
		{
			get
			{
				return this._CenaUlgowa;
			}
			set
			{
				if ((this._CenaUlgowa != value))
				{
					this.OnCenaUlgowaChanging(value);
					this.SendPropertyChanging();
					this._CenaUlgowa = value;
					this.SendPropertyChanged("CenaUlgowa");
					this.OnCenaUlgowaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LiczbaBiletow", DbType="Int")]
		public System.Nullable<int> LiczbaBiletow
		{
			get
			{
				return this._LiczbaBiletow;
			}
			set
			{
				if ((this._LiczbaBiletow != value))
				{
					this.OnLiczbaBiletowChanging(value);
					this.SendPropertyChanging();
					this._LiczbaBiletow = value;
					this.SendPropertyChanged("LiczbaBiletow");
					this.OnLiczbaBiletowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Obrazek", DbType="VarChar(50)")]
		public string Obrazek
		{
			get
			{
				return this._Obrazek;
			}
			set
			{
				if ((this._Obrazek != value))
				{
					this.OnObrazekChanging(value);
					this.SendPropertyChanging();
					this._Obrazek = value;
					this.SendPropertyChanged("Obrazek");
					this.OnObrazekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Szczegoly", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Szczegoly
		{
			get
			{
				return this._Szczegoly;
			}
			set
			{
				if ((this._Szczegoly != value))
				{
					this.OnSzczegolyChanging(value);
					this.SendPropertyChanging();
					this._Szczegoly = value;
					this.SendPropertyChanged("Szczegoly");
					this.OnSzczegolyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SprzedaneBilety", DbType="Int")]
		public System.Nullable<int> SprzedaneBilety
		{
			get
			{
				return this._SprzedaneBilety;
			}
			set
			{
				if ((this._SprzedaneBilety != value))
				{
					this.OnSprzedaneBiletyChanging(value);
					this.SendPropertyChanging();
					this._SprzedaneBilety = value;
					this.SendPropertyChanged("SprzedaneBilety");
					this.OnSprzedaneBiletyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Imprezy_Koszyk", Storage="_Koszyks", ThisKey="ImprezaID", OtherKey="ImprezaID")]
		public EntitySet<Koszyk> Koszyks
		{
			get
			{
				return this._Koszyks;
			}
			set
			{
				this._Koszyks.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Koszyks(Koszyk entity)
		{
			this.SendPropertyChanging();
			entity.Imprezy = this;
		}
		
		private void detach_Koszyks(Koszyk entity)
		{
			this.SendPropertyChanging();
			entity.Imprezy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Koszyk")]
	public partial class Koszyk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RekordID;
		
		private string _Identyfikator;
		
		private System.Nullable<System.DateTime> _DataUtworzenia;
		
		private System.Nullable<int> _ImprezaID;
		
		private System.Nullable<int> _Ilosc;
		
		private string _TypKlienta;
		
		private EntityRef<Imprezy> _Imprezy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRekordIDChanging(int value);
    partial void OnRekordIDChanged();
    partial void OnIdentyfikatorChanging(string value);
    partial void OnIdentyfikatorChanged();
    partial void OnDataUtworzeniaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataUtworzeniaChanged();
    partial void OnImprezaIDChanging(System.Nullable<int> value);
    partial void OnImprezaIDChanged();
    partial void OnIloscChanging(System.Nullable<int> value);
    partial void OnIloscChanged();
    partial void OnTypKlientaChanging(string value);
    partial void OnTypKlientaChanged();
    #endregion
		
		public Koszyk()
		{
			this._Imprezy = default(EntityRef<Imprezy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RekordID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RekordID
		{
			get
			{
				return this._RekordID;
			}
			set
			{
				if ((this._RekordID != value))
				{
					this.OnRekordIDChanging(value);
					this.SendPropertyChanging();
					this._RekordID = value;
					this.SendPropertyChanged("RekordID");
					this.OnRekordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identyfikator", DbType="NVarChar(50)")]
		public string Identyfikator
		{
			get
			{
				return this._Identyfikator;
			}
			set
			{
				if ((this._Identyfikator != value))
				{
					this.OnIdentyfikatorChanging(value);
					this.SendPropertyChanging();
					this._Identyfikator = value;
					this.SendPropertyChanged("Identyfikator");
					this.OnIdentyfikatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataUtworzenia", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataUtworzenia
		{
			get
			{
				return this._DataUtworzenia;
			}
			set
			{
				if ((this._DataUtworzenia != value))
				{
					this.OnDataUtworzeniaChanging(value);
					this.SendPropertyChanging();
					this._DataUtworzenia = value;
					this.SendPropertyChanged("DataUtworzenia");
					this.OnDataUtworzeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImprezaID", DbType="Int")]
		public System.Nullable<int> ImprezaID
		{
			get
			{
				return this._ImprezaID;
			}
			set
			{
				if ((this._ImprezaID != value))
				{
					if (this._Imprezy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnImprezaIDChanging(value);
					this.SendPropertyChanging();
					this._ImprezaID = value;
					this.SendPropertyChanged("ImprezaID");
					this.OnImprezaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc", DbType="Int")]
		public System.Nullable<int> Ilosc
		{
			get
			{
				return this._Ilosc;
			}
			set
			{
				if ((this._Ilosc != value))
				{
					this.OnIloscChanging(value);
					this.SendPropertyChanging();
					this._Ilosc = value;
					this.SendPropertyChanged("Ilosc");
					this.OnIloscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypKlienta", DbType="VarChar(50)")]
		public string TypKlienta
		{
			get
			{
				return this._TypKlienta;
			}
			set
			{
				if ((this._TypKlienta != value))
				{
					this.OnTypKlientaChanging(value);
					this.SendPropertyChanging();
					this._TypKlienta = value;
					this.SendPropertyChanged("TypKlienta");
					this.OnTypKlientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Imprezy_Koszyk", Storage="_Imprezy", ThisKey="ImprezaID", OtherKey="ImprezaID", IsForeignKey=true)]
		public Imprezy Imprezy
		{
			get
			{
				return this._Imprezy.Entity;
			}
			set
			{
				Imprezy previousValue = this._Imprezy.Entity;
				if (((previousValue != value) 
							|| (this._Imprezy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Imprezy.Entity = null;
						previousValue.Koszyks.Remove(this);
					}
					this._Imprezy.Entity = value;
					if ((value != null))
					{
						value.Koszyks.Add(this);
						this._ImprezaID = value.ImprezaID;
					}
					else
					{
						this._ImprezaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Imprezy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WidokCenaKoszyka")]
	public partial class WidokCenaKoszyka
	{
		
		private int _ImprezaID;
		
		private string _Identyfikator;
		
		private System.Nullable<decimal> _CenaPodstawowa;
		
		private System.Nullable<decimal> _CenaStudent;
		
		private System.Nullable<decimal> _CenaUlgowa;
		
		private System.Nullable<int> _Ilosc;
		
		private string _TypKlienta;
		
		public WidokCenaKoszyka()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImprezaID", DbType="Int NOT NULL")]
		public int ImprezaID
		{
			get
			{
				return this._ImprezaID;
			}
			set
			{
				if ((this._ImprezaID != value))
				{
					this._ImprezaID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identyfikator", DbType="NVarChar(50)")]
		public string Identyfikator
		{
			get
			{
				return this._Identyfikator;
			}
			set
			{
				if ((this._Identyfikator != value))
				{
					this._Identyfikator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaPodstawowa", DbType="Money")]
		public System.Nullable<decimal> CenaPodstawowa
		{
			get
			{
				return this._CenaPodstawowa;
			}
			set
			{
				if ((this._CenaPodstawowa != value))
				{
					this._CenaPodstawowa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaStudent", DbType="Money")]
		public System.Nullable<decimal> CenaStudent
		{
			get
			{
				return this._CenaStudent;
			}
			set
			{
				if ((this._CenaStudent != value))
				{
					this._CenaStudent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaUlgowa", DbType="Money")]
		public System.Nullable<decimal> CenaUlgowa
		{
			get
			{
				return this._CenaUlgowa;
			}
			set
			{
				if ((this._CenaUlgowa != value))
				{
					this._CenaUlgowa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilosc", DbType="Int")]
		public System.Nullable<int> Ilosc
		{
			get
			{
				return this._Ilosc;
			}
			set
			{
				if ((this._Ilosc != value))
				{
					this._Ilosc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypKlienta", DbType="VarChar(50)")]
		public string TypKlienta
		{
			get
			{
				return this._TypKlienta;
			}
			set
			{
				if ((this._TypKlienta != value))
				{
					this._TypKlienta = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zamowienia")]
	public partial class Zamowienia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ZamowienieID;
		
		private string _Klient;
		
		private System.DateTime _DataZamowienia;
		
		private EntitySet<ZlecenieSzczegoly> _ZlecenieSzczegolies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZamowienieIDChanging(int value);
    partial void OnZamowienieIDChanged();
    partial void OnKlientChanging(string value);
    partial void OnKlientChanged();
    partial void OnDataZamowieniaChanging(System.DateTime value);
    partial void OnDataZamowieniaChanged();
    #endregion
		
		public Zamowienia()
		{
			this._ZlecenieSzczegolies = new EntitySet<ZlecenieSzczegoly>(new Action<ZlecenieSzczegoly>(this.attach_ZlecenieSzczegolies), new Action<ZlecenieSzczegoly>(this.detach_ZlecenieSzczegolies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZamowienieID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ZamowienieID
		{
			get
			{
				return this._ZamowienieID;
			}
			set
			{
				if ((this._ZamowienieID != value))
				{
					this.OnZamowienieIDChanging(value);
					this.SendPropertyChanging();
					this._ZamowienieID = value;
					this.SendPropertyChanged("ZamowienieID");
					this.OnZamowienieIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Klient", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Klient
		{
			get
			{
				return this._Klient;
			}
			set
			{
				if ((this._Klient != value))
				{
					this.OnKlientChanging(value);
					this.SendPropertyChanging();
					this._Klient = value;
					this.SendPropertyChanged("Klient");
					this.OnKlientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataZamowienia", DbType="DateTime NOT NULL")]
		public System.DateTime DataZamowienia
		{
			get
			{
				return this._DataZamowienia;
			}
			set
			{
				if ((this._DataZamowienia != value))
				{
					this.OnDataZamowieniaChanging(value);
					this.SendPropertyChanging();
					this._DataZamowienia = value;
					this.SendPropertyChanged("DataZamowienia");
					this.OnDataZamowieniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Zamowienia_ZlecenieSzczegoly", Storage="_ZlecenieSzczegolies", ThisKey="ZamowienieID", OtherKey="ZamowienieID")]
		public EntitySet<ZlecenieSzczegoly> ZlecenieSzczegolies
		{
			get
			{
				return this._ZlecenieSzczegolies;
			}
			set
			{
				this._ZlecenieSzczegolies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ZlecenieSzczegolies(ZlecenieSzczegoly entity)
		{
			this.SendPropertyChanging();
			entity.Zamowienia = this;
		}
		
		private void detach_ZlecenieSzczegolies(ZlecenieSzczegoly entity)
		{
			this.SendPropertyChanging();
			entity.Zamowienia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZlecenieSzczegoly")]
	public partial class ZlecenieSzczegoly : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SzczegolyZleceniaID;
		
		private System.Nullable<int> _ZamowienieID;
		
		private System.Nullable<int> _ImprezaID;
		
		private System.Nullable<decimal> _Cena;
		
		private string _Kod;
		
		private string _TypKlienta;
		
		private System.Nullable<bool> _Zaplacono;
		
		private EntityRef<Zamowienia> _Zamowienia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSzczegolyZleceniaIDChanging(int value);
    partial void OnSzczegolyZleceniaIDChanged();
    partial void OnZamowienieIDChanging(System.Nullable<int> value);
    partial void OnZamowienieIDChanged();
    partial void OnImprezaIDChanging(System.Nullable<int> value);
    partial void OnImprezaIDChanged();
    partial void OnCenaChanging(System.Nullable<decimal> value);
    partial void OnCenaChanged();
    partial void OnKodChanging(string value);
    partial void OnKodChanged();
    partial void OnTypKlientaChanging(string value);
    partial void OnTypKlientaChanged();
    partial void OnZaplaconoChanging(System.Nullable<bool> value);
    partial void OnZaplaconoChanged();
    #endregion
		
		public ZlecenieSzczegoly()
		{
			this._Zamowienia = default(EntityRef<Zamowienia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SzczegolyZleceniaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SzczegolyZleceniaID
		{
			get
			{
				return this._SzczegolyZleceniaID;
			}
			set
			{
				if ((this._SzczegolyZleceniaID != value))
				{
					this.OnSzczegolyZleceniaIDChanging(value);
					this.SendPropertyChanging();
					this._SzczegolyZleceniaID = value;
					this.SendPropertyChanged("SzczegolyZleceniaID");
					this.OnSzczegolyZleceniaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZamowienieID", DbType="Int")]
		public System.Nullable<int> ZamowienieID
		{
			get
			{
				return this._ZamowienieID;
			}
			set
			{
				if ((this._ZamowienieID != value))
				{
					if (this._Zamowienia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnZamowienieIDChanging(value);
					this.SendPropertyChanging();
					this._ZamowienieID = value;
					this.SendPropertyChanged("ZamowienieID");
					this.OnZamowienieIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImprezaID", DbType="Int")]
		public System.Nullable<int> ImprezaID
		{
			get
			{
				return this._ImprezaID;
			}
			set
			{
				if ((this._ImprezaID != value))
				{
					this.OnImprezaIDChanging(value);
					this.SendPropertyChanging();
					this._ImprezaID = value;
					this.SendPropertyChanged("ImprezaID");
					this.OnImprezaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena", DbType="Money")]
		public System.Nullable<decimal> Cena
		{
			get
			{
				return this._Cena;
			}
			set
			{
				if ((this._Cena != value))
				{
					this.OnCenaChanging(value);
					this.SendPropertyChanging();
					this._Cena = value;
					this.SendPropertyChanged("Cena");
					this.OnCenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kod", DbType="VarChar(50)")]
		public string Kod
		{
			get
			{
				return this._Kod;
			}
			set
			{
				if ((this._Kod != value))
				{
					this.OnKodChanging(value);
					this.SendPropertyChanging();
					this._Kod = value;
					this.SendPropertyChanged("Kod");
					this.OnKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypKlienta", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TypKlienta
		{
			get
			{
				return this._TypKlienta;
			}
			set
			{
				if ((this._TypKlienta != value))
				{
					this.OnTypKlientaChanging(value);
					this.SendPropertyChanging();
					this._TypKlienta = value;
					this.SendPropertyChanged("TypKlienta");
					this.OnTypKlientaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zaplacono", DbType="Bit")]
		public System.Nullable<bool> Zaplacono
		{
			get
			{
				return this._Zaplacono;
			}
			set
			{
				if ((this._Zaplacono != value))
				{
					this.OnZaplaconoChanging(value);
					this.SendPropertyChanging();
					this._Zaplacono = value;
					this.SendPropertyChanged("Zaplacono");
					this.OnZaplaconoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Zamowienia_ZlecenieSzczegoly", Storage="_Zamowienia", ThisKey="ZamowienieID", OtherKey="ZamowienieID", IsForeignKey=true)]
		public Zamowienia Zamowienia
		{
			get
			{
				return this._Zamowienia.Entity;
			}
			set
			{
				Zamowienia previousValue = this._Zamowienia.Entity;
				if (((previousValue != value) 
							|| (this._Zamowienia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Zamowienia.Entity = null;
						previousValue.ZlecenieSzczegolies.Remove(this);
					}
					this._Zamowienia.Entity = value;
					if ((value != null))
					{
						value.ZlecenieSzczegolies.Add(this);
						this._ZamowienieID = value.ZamowienieID;
					}
					else
					{
						this._ZamowienieID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Zamowienia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
