//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string ampm {
            get {
                return ResourceManager.GetString("ampm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aukcja.
        /// </summary>
        public static string Auction {
            get {
                return ResourceManager.GetString("Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aukcja zostala usunieta.
        /// </summary>
        public static string AuctionDeleted {
            get {
                return ResourceManager.GetString("AuctionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupno/Sprzedzaz.
        /// </summary>
        public static string AuctionDirection {
            get {
                return ResourceManager.GetString("AuctionDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeprszamy  -  wskazana aukcja nie istnieje lub została usunięta..
        /// </summary>
        public static string AuctionDoesntExist {
            get {
                return ResourceManager.GetString("AuctionDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa Aukcji.
        /// </summary>
        public static string AuctionName {
            get {
                return ResourceManager.GetString("AuctionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono aukcji.
        /// </summary>
        public static string AuctionNotFound {
            get {
                return ResourceManager.GetString("AuctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer aukcji.
        /// </summary>
        public static string AuctionNumber {
            get {
                return ResourceManager.GetString("AuctionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aukcje.
        /// </summary>
        public static string Auctions {
            get {
                return ResourceManager.GetString("Auctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana [%].
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miasto.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejdz do Aukcji.
        /// </summary>
        public static string ClickForUpcomingAuction {
            get {
                return ResourceManager.GetString("ClickForUpcomingAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrobione.
        /// </summary>
        public static string closeText {
            get {
                return ResourceManager.GetString("closeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło i potwierdzenie hasła nie pasują do siebie.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Potwierdzenie hasła.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kraj.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waluta.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obecna cena.
        /// </summary>
        public static string CurrentPrice {
            get {
                return ResourceManager.GetString("CurrentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość oferty nie spełnia warunków aukcji.
        /// </summary>
        public static string CurrentPriceChangeToSmall {
            get {
                return ResourceManager.GetString("CurrentPriceChangeToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teraz.
        /// </summary>
        public static string currentText {
            get {
                return ResourceManager.GetString("currentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można zapisać zmian. Spróbuj ponownie.administrator..
        /// </summary>
        public static string DataException {
            get {
                return ResourceManager.GetString("DataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dane oferty.
        /// </summary>
        public static string DataOffer {
            get {
                return ResourceManager.GetString("DataOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niemiecki.
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usun.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie usuwania.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunieto.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email jest nieprawidłowy.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email jest wymagany.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Włączona.
        /// </summary>
        public static string EnableDisable {
            get {
                return ResourceManager.GetString("EnableDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec Aukcji.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd w dostępie do aukcji.
        /// </summary>
        public static string ErrorAccessingAuction {
            get {
                return ResourceManager.GetString("ErrorAccessingAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; musi byc puzniejszy od  &apos;{1}&apos;.
        /// </summary>
        public static string ErrorEndTimeGreaterStartTime {
            get {
                return ResourceManager.GetString("ErrorEndTimeGreaterStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; musi byc wiekszy od obecnej godziny.
        /// </summary>
        public static string ErrorStartTimeGreaterNow {
            get {
                return ResourceManager.GetString("ErrorStartTimeGreaterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Imie.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imie jest wymagane.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprzedaz.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy w Inbid.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godzina.
        /// </summary>
        public static string hourText {
            get {
                return ResourceManager.GetString("hourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Język.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język jest wymagany.
        /// </summary>
        public static string LanguageRequired {
            get {
                return ResourceManager.GetString("LanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Nazwisko.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko jest wymagane.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        public static string LoginWelcome {
            get {
                return ResourceManager.GetString("LoginWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj się.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie ma aukcji?.
        /// </summary>
        public static string LostQuestion {
            get {
                return ResourceManager.GetString("LostQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postąpienie.
        /// </summary>
        public static string MinJump {
            get {
                return ResourceManager.GetString("MinJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuta.
        /// </summary>
        public static string minuteText {
            get {
                return ResourceManager.GetString("minuteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd MMM.
        /// </summary>
        public static string MMMdd {
            get {
                return ResourceManager.GetString("MMMdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string ModelDescription {
            get {
                return ResourceManager.GetString("ModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis jest wymagny .
        /// </summary>
        public static string ModelDescriptionRequired {
            get {
                return ResourceManager.GetString("ModelDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd&apos; &apos;MMMM&apos; &apos;yyyy.
        /// </summary>
        public static string MonthDayYear {
            get {
                return ResourceManager.GetString("MonthDayYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa Oferenta.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa Aukcji.
        /// </summary>
        public static string NameAuction {
            get {
                return ResourceManager.GetString("NameAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono aukcji.
        /// </summary>
        public static string NoAuctionFound {
            get {
                return ResourceManager.GetString("NoAuctionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następna &gt;.
        /// </summary>
        public static string PageNext {
            get {
                return ResourceManager.GetString("PageNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona {0} z {1}.
        /// </summary>
        public static string PageOf {
            get {
                return ResourceManager.GetString("PageOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Poprzednia.
        /// </summary>
        public static string PagePrev {
            get {
                return ResourceManager.GetString("PagePrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło musi mieć co najmniej 6 znaków..
        /// </summary>
        public static string PasswordLong {
            get {
                return ResourceManager.GetString("PasswordLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jest wymagane.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon jest niepoprawny.
        /// </summary>
        public static string PhoneInvalid {
            get {
                return ResourceManager.GetString("PhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdz jezeli chcesz usunac aukcje.
        /// </summary>
        public static string PleaseConfirmCancelDinner {
            get {
                return ResourceManager.GetString("PleaseConfirmCancelDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Pocztowy.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Województwo.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestruj.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kupno.
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osoba.
        /// </summary>
        public static string RSVP {
            get {
                return ResourceManager.GetString("RSVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osoby.
        /// </summary>
        public static string RSVPs {
            get {
                return ResourceManager.GetString("RSVPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunda.
        /// </summary>
        public static string secondText {
            get {
                return ResourceManager.GetString("secondText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Początkowa cena.
        /// </summary>
        public static string StartPrice {
            get {
                return ResourceManager.GetString("StartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Początek aukcji.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz Godzine.
        /// </summary>
        public static string timeOnlyTitle {
            get {
                return ResourceManager.GetString("timeOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas.
        /// </summary>
        public static string timeText {
            get {
                return ResourceManager.GetString("timeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa Użytkownika.
        /// </summary>
        public static string UserN {
            get {
                return ResourceManager.GetString("UserN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Nazwa użytkownika.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika jest wymagana.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokaż najlepszą oferte.
        /// </summary>
        public static string ViewTopOffer {
            get {
                return ResourceManager.GetString("ViewTopOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy w Inbid.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        public static string with {
            get {
                return ResourceManager.GetString("with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tak.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie jesteś właścicielem tej aukcji.
        /// </summary>
        public static string YouDoNotOwnThisAuction {
            get {
                return ResourceManager.GetString("YouDoNotOwnThisAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie aukcji zakoñczylo sie powodzeniem.
        /// </summary>
        public static string YourAuctionDeleted {
            get {
                return ResourceManager.GetString("YourAuctionDeleted", resourceCulture);
            }
        }
    }
}
